### ISSUE TITLE
Configure celery

### ISSUE THREAD

**Issue by joewandy** [joewandy/FrAnK#1]
Received the following message when submitting a task to celery. Seems that it is not configured properly:

```
(FrAnK-ZDqaA4t0) joewandy@joe-ubuntu:~/git/FrAnK/django_projects$ ./run_celery.sh 
[2019-02-15 17:22:18,176: WARNING/MainProcess] /home/joewandy/.local/share/virtualenvs/FrAnK-ZDqaA4t0/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
 
 -------------- celery@joe-ubuntu v3.1.18 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-4.18.0-11-generic-x86_64-with-Ubuntu-18.10-cosmic
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x7f663e8c0110 (.default.Loader)
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

[2019-02-15 17:22:19,221: WARNING/MainProcess] celery@joe-ubuntu ready.
[2019-02-15 17:23:01,490: ERROR/MainProcess] Received unregistered task of type 'frank.tasks.msn_generate_peak_list'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{'utc': True, 'chord': None, 'args': (u'1', 3, None), 'retries': 0, 'expires': None, 'task': 'frank.tasks.msn_generate_peak_list', 'callbacks': None, 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, 'id': 'b156ce97-705e-4019-9381-71a0a90b0f67'} (239b)
Traceback (most recent call last):
  File "/home/joewandy/.local/share/virtualenvs/FrAnK-ZDqaA4t0/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 455, in on_task_received
    strategies[name](message, body,
KeyError: 'frank.tasks.msn_generate_peak_list'
```

**Comment by joewandy** [comment]
Added https://github.com/glasgowcompbio/FrAnK/commit/d2eb8f2a2c2b87d99efa2b4c2625adaa3d27bf0f but still can't submit task. Seems that the frank app is not registered properly with celery.

**Comment by sjgreig27** [comment]
~/Git/FrAnK/django_projects$ python manage.py celery worker --settings=django_projects.settings
 
 -------------- celery@scottiedog27-HP-15-Notebook-PC v3.1.18 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x7f362ac82cd0 (djcelery.loaders.DjangoLoader)
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     database
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

/home/scottiedog27/Git/FrAnK/env/local/lib/python2.7/site-packages/djcelery/loaders.py:136: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warn('Using settings.DEBUG leads to a memory leak, never '

WARNING 2019-02-25 23:08:29,799 loaders.py:136 0 0 0 | /home/scottiedog27/Git/FrAnK/env/local/lib/python2.7/site-packages/djcelery/loaders.py:136: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warn('Using settings.DEBUG leads to a memory leak, never '

celery@scottiedog27-HP-15-Notebook-PC ready.
WARNING 2019-02-25 23:15:30,282 fragfile_extraction.py:274 0 0 0 | MS2 duplicates have been found in this fragmentation & are: [[779, 246.05, 205.41, 6414.46923828125], [779, 371.1833, 205.41, 8455.6083984375], [980, 53.0026, 239.89, 10380.3916015625], [980, 57.0702, 239.89, 14702.95703125], [980, 105.0702, 239.89, 7599.84912109375], [1250, 53.0389, 284.365, 12870.123046875], [1250, 67.0545, 284.365, 6326.9326171875], [1250, 79.0542, 284.365, 6067.22216796875], [1250, 80.0495, 284.365, 5201.46630859375], [1250, 91.0542, 284.365, 13672.91796875], [1250, 109.0526, 284.365, 8941.5771484375], [1462, 59.0495, 321.258, 108965.9375], [1462, 192.1021, 321.258, 5645.01611328125], [1606, 53.0388, 345.103, 6410.34423828125], [1701, 53.0388, 361.317, 5962.009765625], [1701, 96.0441, 361.317, 12122.0380859375], [1715, 89.0386, 362.957, 16707.712890625], [1798, 70.0651, 377.378, 22400.484375], [1798, 152.0703, 377.378, 58260.1328125], [1798, 70.0651, 377.378, 5293.01318359375], [1798, 79.0542, 377.378, 9136.9794921875], [1798, 81.0333, 377.378, 7757.94482421875], [1798, 96.0808, 377.378, 5004.376953125], [1917, 56.0497, 396.807, 8733.0654296875], [1917, 58.0655, 396.807, 6947.62109375], [1917, 70.0652, 396.807, 17482.033203125], [1917, 82.065, 396.807, 34186.2578125], [1917, 84.0807, 396.807, 22111.69921875], [1917, 86.0602, 396.807, 51190.56640625], [1917, 110.097, 396.807, 5974.4853515625], [1917, 111.0276, 396.807, 9975.7509765625], [1917, 128.1074, 396.807, 85024.5390625], [2165, 55.0182, 437.038, 11278.1748046875], [2165, 68.0498, 437.038, 9519.513671875], [2165, 80.0576, 437.038, 32117.275390625], [2165, 81.0333, 437.038, 16174.576171875], [2165, 81.0527, 437.038, 14629.7197265625], [2165, 81.0575, 437.038, 9326.2978515625], [2165, 83.0489, 437.038, 13824.98828125], [2165, 84.0807, 437.038, 10016.673828125], [2165, 95.0608, 437.038, 45348.2265625], [2165, 95.0687, 437.038, 9837.3974609375], [2165, 97.0764, 437.038, 30514.265625], [2165, 97.0846, 437.038, 11217.9658203125], [2165, 106.065, 437.038, 7252.4111328125], [2165, 107.0686, 437.038, 25577.548828125], [2165, 124.0712, 437.038, 7118.13330078125], [2165, 125.0708, 437.038, 75133.609375], [2165, 134.06, 437.038, 8493.3095703125], [2165, 135.0638, 437.038, 482680.71875], [2165, 139.0396, 437.038, 101171.40625], [2165, 153.0748, 437.038, 409352.25], [2165, 171.0766, 437.038, 51619.40625], [2165, 171.0851, 437.038, 63695.8125], [2345, 80.0495, 465.402, 11651.4658203125], [2345, 82.029, 465.402, 5413.26513671875], [2345, 109.0397, 465.402, 49154.87890625], [2345, 126.0665, 465.402, 204743.5625], [2345, 126.0745, 465.402, 5656.2998046875], [2424, 56.0498, 477.914, 22283.296875], [2424, 60.0448, 477.914, 8242.8486328125], [2424, 84.0449, 477.914, 7390.54296875], [2536, 53.039, 494.747, 16803.6875], [2536, 120.038, 494.747, 6902.64697265625], [2536, 121.065, 494.747, 111222.546875], [2536, 138.0589, 494.747, 56699.8828125], [2536, 138.0683, 494.747, 101971.9765625], [2613, 60.0447, 507.489, 7834.638671875], [2613, 84.0442, 507.489, 24101.21875], [2613, 88.0218, 507.489, 6195.3564453125], [2613, 116.0344, 507.489, 7775.3515625], [2642, 60.0559, 512.17, 77741.2265625], [2681, 70.0651, 518.554, 8618.3544921875], [2681, 118.0861, 518.554, 6819.07177734375], [3045, 55.0547, 578.163, 65288.8515625], [3045, 57.045, 578.163, 7682.5302734375], [3045, 86.0601, 578.163, 6972.0400390625], [3045, 87.0439, 578.163, 11363.7021484375], [3045, 101.0597, 578.163, 46628.48828125], [3045, 160.0958, 578.163, 26858.9375], [3045, 160.1323, 578.163, 82040.8359375], [3362, 56.0498, 628.893, 304874.0], [3362, 84.0806, 628.893, 27627.091796875], [4661, 83.0604, 880.763, 5468.14892578125], [4707, 55.0547, 891.146, 15995.13671875], [4707, 60.056, 891.146, 14848.7451171875], [4707, 72.0807, 891.146, 42444.1484375], [4707, 98.0601, 891.146, 23562.904296875], [4707, 131.1293, 891.146, 24251.5859375], [4707, 165.0699, 891.146, 11057.4326171875], [4825, 58.0654, 914.914, 2220775.75], [4825, 60.0809, 914.914, 11531789.0], [4825, 104.1073, 914.914, 27429202.0], [5039, 80.0495, 961.692, 12227.283203125], [5173, 55.0546, 994.149, 14667.337890625], [5173, 83.0856, 994.149, 7432.82275390625], [5173, 125.1079, 994.149, 35511.6171875], [5285, 83.0855, 1025.27, 8037.45849609375], [5285, 108.0804, 1025.27, 5917.3798828125], [6017, 89.0712, 1257.73, 13646.5703125]]

**Comment by sjgreig27** [comment]
Is this the expected behaviour?

**Comment by sjgreig27** [comment]
Fixed in commit 2d0f285899fb8a48c68d293f7b775bf23811b6de. I'll test this in a separate branch before merging into master.

Basically, djcelery and celery configure by two different means in the application. djcelery configuration is much simpler but doesn't look like the module is going to be supported long term. Probably best to go with Celery and upversion to version 4 at some point.

Here are the docs:
http://docs.celeryproject.org/en/3.1/django/first-steps-with-django.html#django-first-steps

**Comment by sjgreig27** [comment]
This is the new output from running the shell script and starting a task

(env) scottiedog27@scottiedog27-HP-15-Notebook-PC:~/Git/FrAnK/django_projects$ ./run_celery.sh 
 
 -------------- celery@scottiedog27-HP-15-Notebook-PC v3.1.18 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         django_projects:0x7f5aa95dcad0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . django_projects.celery.debug_task
  . frank.tasks.clean_filter
  . frank.tasks.magma_batch_search
  . frank.tasks.massbank_batch_search
  . frank.tasks.msn_generate_peak_list
  . frank.tasks.nist_batch_search
  . frank.tasks.precursor_mass_filter
  . frank.tasks.runNetworkSampler
  . frank.tasks.run_default_annotations

/home/scottiedog27/Git/FrAnK/env/local/lib/python2.7/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

WARNING 2019-02-26 20:44:51,462 django.py:265 0 0 0 | /home/scottiedog27/Git/FrAnK/env/local/lib/python2.7/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

WARNING 2019-02-26 20:44:51,463 log.py:228 0 0 0 | celery@scottiedog27-HP-15-Notebook-PC ready.
WARNING 2019-02-26 20:48:38,936 fragfile_extraction.py:274 0 0 0 | MS2 duplicates have been found in this fragmentation & are: [[854, 111.1165, 222.062, 96977.5859375], [966, 53.0026, 242.007, 11780.095703125], [966, 57.0701, 242.007, 68854.03125], [966, 67.0545, 242.007, 12277.9814453125], [966, 69.0701, 242.007, 11592.2470703125], [966, 81.07, 242.007, 11790.3193359375], [966, 85.0648, 242.007, 19769.984375], [966, 103.0545, 242.007, 9837.4814453125], [966, 105.0702, 242.007, 22334.4375], [966, 107.0488, 242.007, 8926.4736328125], [966, 107.0857, 242.007, 28002.310546875], [966, 109.0645, 242.007, 11838.1533203125], [966, 115.0544, 242.007, 12531.625], [966, 117.0704, 242.007, 8761.4990234375], [966, 121.0649, 242.007, 10733.951171875], [966, 129.07, 242.007, 11969.564453125], [966, 133.0645, 242.007, 12537.083984375], [966, 143.0852, 242.007, 11929.7607421875], [966, 189.0924, 242.007, 9197.6474609375], [966, 189.127, 242.007, 9065.3720703125], [966, 261.1492, 242.007, 13207.57421875], [966, 273.1475, 242.007, 9358.48046875], [966, 301.1428, 242.007, 57209.69140625], [966, 301.1824, 242.007, 16919.03515625], [966, 319.1894, 242.007, 15830.001953125], [1079, 53.0388, 260.073, 9857.22265625], [1079, 55.0546, 260.073, 12589.830078125], [1079, 69.0701, 260.073, 7542.0849609375], [1079, 70.0651, 260.073, 6099.3310546875], [1079, 96.0441, 260.073, 7050.74755859375], [1079, 103.0545, 260.073, 6321.5498046875], [1079, 182.0961, 260.073, 61427.23046875], [1079, 182.1171, 260.073, 146598.578125], [1761, 69.0338, 372.967, 16991.166015625], [1761, 85.065, 372.967, 11435.126953125], [1761, 98.0602, 372.967, 53446.40625], [1761, 113.0296, 372.967, 5590.5283203125], [1761, 144.0809, 372.967, 11665.4189453125], [1761, 144.1022, 372.967, 33933.98828125], [2021, 53.0026, 415.956, 42304.94921875], [2021, 68.0498, 415.956, 43237.0078125], [2021, 70.0651, 415.956, 5961082.0], [2118, 53.0026, 431.771, 13496.14453125], [2118, 56.0498, 431.771, 37506.5078125], [2118, 70.0651, 431.771, 647581.625], [2400, 88.0218, 476.16, 7879.20263671875], [2400, 187.0571, 476.16, 5166.982421875], [2400, 187.0717, 476.16, 12937.625], [2400, 187.1081, 476.16, 18718.279296875], [2505, 53.0026, 492.818, 9165.7587890625], [2505, 56.0498, 492.818, 47689.828125], [2505, 70.0652, 492.818, 192810.65625], [2505, 76.0392, 492.818, 74454.390625], [2505, 84.0442, 492.818, 421062.3125], [2505, 88.0218, 492.818, 9310.9736328125], [2505, 116.0712, 492.818, 127412.28125], [2505, 141.0661, 492.818, 8941.81640625], [2830, 84.0807, 546.068, 15079.326171875], [2830, 203.052, 546.068, 53629.3984375], [2886, 56.0497, 555.714, 6683.28076171875], [2886, 57.0336, 555.714, 15308.92578125], [2886, 67.0291, 555.714, 34013.58984375], [2886, 68.0132, 555.714, 34531.89453125], [2886, 68.0327, 555.714, 7775.35986328125], [2886, 68.0498, 555.714, 17856.119140625], [2886, 69.0168, 555.714, 14704.1796875], [2886, 69.0451, 555.714, 110425.0], [2886, 70.0417, 555.714, 6090.70068359375], [2886, 70.0484, 555.714, 48338.28515625], [2886, 72.0806, 555.714, 50233.12890625], [2886, 73.0842, 555.714, 51707.140625], [2886, 80.0495, 555.714, 15491.7509765625], [2886, 84.0807, 555.714, 16152.7822265625], [2886, 92.0495, 555.714, 14010.080078125], [2886, 95.0239, 555.714, 348206.9375], [2886, 95.0432, 555.714, 39880.21484375], [2886, 96.0209, 555.714, 43579.921875], [2886, 100.0394, 555.714, 36738.19921875], [2886, 112.051, 555.714, 2396214.5], [2886, 113.0477, 555.714, 364464.1875], [2886, 113.0546, 555.714, 1719962.25], [2886, 116.0712, 555.714, 15139.0205078125], [2886, 120.0442, 555.714, 7323.8837890625], [2886, 163.0508, 555.714, 13620.564453125], [2886, 167.0447, 555.714, 15583.2958984375], [2964, 68.0498, 568.114, 619636.375], [2964, 70.0651, 568.114, 90713552.0], [3023, 70.0651, 577.58, 7842832.5], [3023, 70.0684, 577.58, 125587.84375], [3023, 71.063, 577.58, 2513827.75], [3023, 71.0688, 577.58, 28237932.0], [3037, 68.0498, 580.351, 3409712.75], [3037, 70.0651, 580.351, 496926272.0], [3037, 116.0795, 580.351, 815249.75], [3204, 56.0498, 607.252, 28326.828125], [3204, 60.0558, 607.252, 7916.15283203125], [3204, 67.0545, 607.252, 6035.83154296875], [3204, 70.0651, 607.252, 428442.8125], [3204, 71.0494, 607.252, 11353.3515625], [3204, 84.0448, 607.252, 163659.296875], [3204, 130.0872, 607.252, 6265.85302734375], [3204, 130.0984, 607.252, 13653.2470703125], [4152, 55.0295, 781.526, 6089.048828125], [4152, 72.0808, 781.526, 15953.7861328125], [4152, 86.0716, 781.526, 39381.328125], [4152, 97.0764, 781.526, 11706.8154296875], [4152, 114.0659, 781.526, 296859.25], [4152, 114.0913, 781.526, 53048.51953125], [4152, 114.1028, 781.526, 35757.546875], [4302, 70.0651, 811.341, 6580.451171875], [4302, 90.0635, 811.341, 8207.033203125], [4856, 89.0601, 923.329, 139187.1875], [4856, 104.1073, 923.329, 152924.3125], [5915, 60.081, 1205.97, 21531.619140625], [5915, 86.0601, 1205.97, 6652.1875], [5915, 104.1073, 1205.97, 52159.01171875]]

**Comment by joewandy** [comment]
Seems like it's working properly in the above! :D I can see tasks being registered in the print.
