### ISSUE TITLE
base.html fails to reverse resolve {% url 'userguide' %}

### ISSUE THREAD

**Issue by sjgreig27** [joewandy/FrAnK#5]
In mytemplates/base.html template, the reverse resolution of {% url 'userguide' %} fails. Does this need to be migrated over from the main PiMP app?

**Comment by joewandy** [comment]
No, that's the user guide for pimp. Just delete that URL.

**Comment by joewandy** [comment]
Fixed in commit https://github.com/glasgowcompbio/FrAnK/commit/3c29d605ecd5e2a1fd5425496d35ad54a0579c5b
